"""
split_pdf.py — Split Iron Arrow history PDF into sections and generate metadata.

Usage:
    python3 split_pdf.py --input "iron-arrow-history.pdf" --output_dir ./section

Outputs:
    sections/         ← split PDFs, one per section
    chunks/           ← 4-layer JSON chunks per section
    resources.xlsx    ← metadata table for the chatbot

──────────────────────────────────────────────────────────────
JSON CHUNK STRUCTURE (4 layers)
──────────────────────────────────────────────────────────────
layer0_index      Always in system prompt. Key/name/description/subsections/
                  one-sentence summary. Never fetched via tool.

layer1_summary    First tool call result. One thematic paragraph + 5 tight
                  narrative bullets covering the whole section at a glance.
                  Sufficient for general "what is this section about?" queries.

layer2_details    Second tool call result. Subsection-by-subsection fact
                  bullets — names, dates, key events, causal logic. Sufficient
                  for specific factual queries without loading the full PDF text.

layer3_full_text  Third tool call result (rarely needed). Raw text extracted
                  from the split PDF at runtime — for exact quotes, fine-grained
                  detail, or anything layer2_details doesn't cover.

Layers 1 and 2 are generated by Claude (claude-sonnet-4-6) during preprocessing
using the extracted PDF text as source. Layer 3 is extracted live from the split
PDF at query time; it is NOT stored in the JSON to keep chunk files lightweight.
──────────────────────────────────────────────────────────────
"""

import argparse
import json
import os
import textwrap
import time

import pandas as pd
from anthropic import Anthropic
from pypdf import PdfReader, PdfWriter
from config import (ANTHROPIC_API_KEY)

# ── Anthropic client ──────────────────────────────────────────────────────────
client = Anthropic(api_key=ANTHROPIC_API_KEY)   # reads ANTHROPIC_API_KEY from environment

# ── Section definitions ───────────────────────────────────────────────────────
# page numbers are 0-indexed (PDF page 1 = index 0).
# Adjust start_page / end_page after you inspect your actual PDF.
SECTIONS = [
    {
        "key":         "front_matter",
        "name":        "Front Matter (Invocation & Introduction)",
        "start_page":  0,
        "end_page":    4,
        "description": "Invocation and Introduction to Iron Arrow history.",
        "section_num": 0,
        "subsections": ["Invocation", "Introduction"],
    },
    {
        "key":         "section_01_beginnings",
        "name":        "Section One: The Beginnings",
        "start_page":  5,
        "end_page":    27,
        "description": "Origins of Iron Arrow: Osceola, Bowman Foster Ashe, Tony Tommie, "
                       "the founding nine, and early history.",
        "section_num": 1,
        "subsections": [
            "Osceola", "Bowman Foster Ashe", "Tony Tommie",
            "The Idea the Name and the First Meeting",
            "The Founding Nine and the Petition", "A Riddle",
            "Traveling to Florida", "Bits and Pieces",
            "A Personal History of the Early Years",
        ],
    },
    {
        "key":         "section_02_intervening_years",
        "name":        "Section Two: The Intervening Years",
        "start_page":  28,
        "end_page":    65,
        "description": "Iron Arrow during the Great Depression and World War II.",
        "section_num": 2,
        "subsections": ["The Great Depression", "World War II and an Iron Arrow Pow-Wow"],
    },
    {
        "key":         "section_03_after_the_war",
        "name":        "Section Three: After the War",
        "start_page":  66,
        "end_page":    86,
        "description": "Post-war era: Doc Adams, ritual development, national expansion, "
                       "and the Ashe statue.",
        "section_num": 3,
        "subsections": [
            "Doc Adams Arrives", "Docs Tapping and the Ritual",
            "Doc and Dr Ashe", "The Tradition Prospers",
            "An Old Timers Round-Up", "National Geographic Photo",
            "Dr Ashe Signs the Charter", "Bits and Pieces",
            "The Ashe Statue", "A Story", "Anguish",
            "Going National", "Bits and Pieces",
        ],
    },
    {
        "key":         "section_04_law_school",
        "name":        "Section Four: Law School Domination",
        "start_page":  87,
        "end_page":    96,
        "description": "Iron Arrow's Law School era, lawyer chiefs, and Henry King Stanford.",
        "section_num": 4,
        "subsections": [
            "An Iron Arrow Election", "The Lawyer Chiefs",
            "Bits and Pieces", "Medical School Campus", "Henry King Stanford",
        ],
    },
    {
        "key":         "section_05_micco_years",
        "name":        "Section Five: 1968–1976 The Micco Years",
        "start_page":  97,
        "end_page":    101,
        "description": "The Micco years: ritual, the ball, and increasing visibility.",
        "section_num": 5,
        "subsections": ["The Ritual", "The Ball", "Increasing Visibility"],
    },
    {
        "key":         "section_06_selection_tapping",
        "name":        "Section Six: Selection, Tapping, Luncheons, Initiation",
        "start_page":  102,
        "end_page":    117,
        "description": "How members are selected, tapping ceremonies, luncheons, "
                       "initiation, and the feminist challenge.",
        "section_num": 6,
        "subsections": [
            "Selection", "Tapping", "Tapping Luncheons",
            "The Initiation", "The Feminist Challenge", "Bits and Pieces",
        ],
    },
    {
        "key":         "section_07_activities",
        "name":        "Section Seven: Activities",
        "start_page":  118,
        "end_page":    131,
        "description": "Iron Arrow activities: Pigeon Key, James Hutchinson Fund, "
                       "Lethal Yellowing, Lignum Vitae, typical year, and epilogue.",
        "section_num": 7,
        "subsections": [
            "Pigeon Key", "The James Hutchinson Fund", "Lethal Yellowing",
            "Lignum Vitae", "A Typical Year", "A Celebration", "Epilogue",
        ],
    },
    {
        "key":         "section_08_paraphernalia",
        "name":        "Section Eight: Paraphernalia",
        "start_page":  132,
        "end_page":    -1,
        "description": "Iron Arrow paraphernalia: Seminole jackets, the arrow, pins, "
                       "the new beginning, football glory years, and quick-reference facts.",
        "section_num": 8,
        "subsections": [
            "Seminole Jackets", "The Arrow", "Ashe In-Memoriam Honor",
            "Iron Arrow Pins", "Bits and Pieces",
            "The New Beginning", "Iron Arrow at a Glance",
            "The Football Glory Years",
        ],
    },
]


# ── PDF helpers ───────────────────────────────────────────────────────────────

def extract_text_from_pages(reader: PdfReader, start: int, end: int) -> str:
    pages = reader.pages[start: end + 1] if end >= 0 else reader.pages[start:]
    return "\n".join(p.extract_text() or "" for p in pages)


# ── Layer 0 ───────────────────────────────────────────────────────────────────

def build_layer0(section: dict, pdf_filename: str) -> dict:
    one_sentence = (
        f"{section['name']}: {section['description']} "
        f"({len(section['subsections'])} subsections)"
    )
    return {
        "key":                 section["key"],
        "section_num":         section["section_num"],
        "name":                section["name"],
        "description":         section["description"],
        "subsections":         section["subsections"],
        "source_pdf":          pdf_filename,
        "start_page":          section["start_page"] + 1,
        "end_page":            section["end_page"] + 1 if section["end_page"] >= 0 else "end",
        "one_sentence_summary": one_sentence,
    }


# ── Claude generation helpers ─────────────────────────────────────────────────

def _call_claude(system: str, user: str, max_tokens: int = 2000) -> str:
    """Single Claude call; returns the text content."""
    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=max_tokens,
        system=system,
        messages=[{"role": "user", "content": user}],
    )
    return response.content[0].text.strip()


def build_layer1_summary(section: dict, full_text: str) -> dict:
    """
    Layer 1: one thematic paragraph + 5 narrative bullets.
    Format mirrors the example:
        <paragraph>

        * bullet 1
        * bullet 2
        ...
    """
    system = textwrap.dedent("""\
        You are a precise academic summarizer working on an Iron Arrow Honor Society
        history chatbot. Your output is used as a Layer 1 retrieval result — the first
        thing a user sees when they ask a general question about a section.

        Rules:
        - Write one concise thematic paragraph (2–3 sentences) that orients the reader
          to what the section is about and why it matters in the context of Iron Arrow.
        - Follow it with exactly 5 bullet points (use "* " prefix) that each capture one
          major narrative thread or theme of the section. Each bullet should be one full
          sentence. Do not use sub-bullets.
        - Do not use headers, bold, or any other markdown beyond the "* " bullets.
        - Do not start with the section name or "This section".
        - Be concrete: name key people, events, or turning points where relevant.
        - Output only the paragraph and bullets — nothing else.
    """)

    user = textwrap.dedent(f"""\
        Section: {section['name']}
        Subsections: {', '.join(section['subsections'])}
        Description: {section['description']}

        Source text (extract):
        {full_text[:6000]}
    """)

    raw = _call_claude(system, user, max_tokens=600)

    # Split into paragraph and bullets
    lines = raw.splitlines()
    paragraph_lines = []
    bullets = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("* "):
            bullets.append(stripped[2:].strip())
        elif stripped and not bullets:
            paragraph_lines.append(stripped)

    paragraph = " ".join(paragraph_lines).strip()
    return {"paragraph": paragraph, "bullets": bullets}


def build_layer2_details(section: dict, full_text: str) -> dict:
    """
    Layer 2: subsection-by-subsection fact bullets.
    Format:
        SUBSECTION NAME
        - fact / detail
        - fact / detail
        ...
    """
    system = textwrap.dedent("""\
        You are a precise academic archivist working on an Iron Arrow Honor Society
        history chatbot. Your output is used as a Layer 2 retrieval result — fetched
        when a user needs specific facts that a brief summary couldn't provide.

        Rules:
        - Organize output by subsection. Write each subsection name in ALL CAPS on its
          own line, followed by bullet points using "- " prefix.
        - For each subsection, capture: key people (full names), key dates, key events,
          causal relationships, direct quotes where they illuminate meaning, and anything
          a researcher would need to answer specific factual questions.
        - Preserve exact names, dates, and numbers from the source — do not paraphrase
          these away.
        - Include direct quotes only where the exact wording adds information that
          paraphrase would lose (e.g., charter text, naming stories, death-scene accounts).
        - Do not write prose paragraphs — every line under a subsection header must be
          a "- " bullet.
        - Do not add a preamble, conclusion, or section overview — jump straight into
          the first subsection header.
        - Output only the structured subsection content — nothing else.
    """)

    user = textwrap.dedent(f"""\
        Section: {section['name']}
        Subsections to cover: {', '.join(section['subsections'])}

        Source text:
        {full_text[:12000]}
    """)

    raw = _call_claude(system, user, max_tokens=3000)
    return {"text": raw}


# ── Main chunk builder ────────────────────────────────────────────────────────

def build_chunk_json(section: dict, full_text: str, pdf_filename: str) -> dict:
    """
    Build the 4-layer JSON chunk for a section.
    Layer 3 (full text) is intentionally omitted — extracted live at query time
    from the split PDF to keep chunk files lightweight.
    """
    print(f"    Generating layer 1 summary…")
    layer1 = build_layer1_summary(section, full_text)
    time.sleep(0.5)   # gentle rate-limit buffer

    print(f"    Generating layer 2 details…")
    layer2 = build_layer2_details(section, full_text)
    time.sleep(0.5)

    return {
        "layer0_index":   build_layer0(section, pdf_filename),
        "layer1_summary": layer1,
        "layer2_details": layer2,
        # layer3_full_text is NOT stored here.
        # app.py extracts it live from sections/<key>.pdf via pypdf.
    }


# ── Split + write ─────────────────────────────────────────────────────────────

def split_pdf(input_path: str, output_dir: str, chunks_dir: str) -> list[dict]:
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(chunks_dir, exist_ok=True)

    reader = PdfReader(input_path)
    total_pages = len(reader.pages)
    print(f"PDF has {total_pages} pages.\n")

    metadata_rows = []

    for section in SECTIONS:
        start = section["start_page"]
        end   = section["end_page"] if section["end_page"] >= 0 else total_pages - 1

        if start >= total_pages:
            print(f"  ⚠ Skipping {section['key']}: start_page {start} ≥ total pages {total_pages}")
            continue

        end = min(end, total_pages - 1)
        print(f"  Processing: {section['key']}  (pages {start+1}–{end+1})")

        # ── Write split PDF ────────────────────────────────────────────────
        writer = PdfWriter()
        for i in range(start, end + 1):
            writer.add_page(reader.pages[i])

        pdf_out = os.path.join(output_dir, f"{section['key']}.pdf")
        with open(pdf_out, "wb") as f:
            writer.write(f)
        print(f"    ✓ PDF written → {pdf_out}")

        # ── Extract text ───────────────────────────────────────────────────
        full_text = extract_text_from_pages(reader, start, end)
        word_count = len(full_text.split())
        print(f"    Extracted {word_count:,} words of source text.")

        # ── Build chunk JSON (calls Claude for layers 1 & 2) ──────────────
        chunk_data = build_chunk_json(section, full_text, os.path.basename(input_path))

        json_out = os.path.join(chunks_dir, f"{section['key']}.json")
        with open(json_out, "w", encoding="utf-8") as f:
            json.dump(chunk_data, f, indent=2, ensure_ascii=False)
        print(f"    ✓ JSON written → {json_out}\n")

        # ── Metadata row for resources.xlsx ───────────────────────────────
        metadata_rows.append({
            "key":         section["key"],
            "name":        section["name"],
            "description": section["description"],
            "section_num": section["section_num"],
            "subsections": "; ".join(section["subsections"]),
            "start_page":  start + 1,
            "end_page":    end + 1,
            "pdf_file":    f"{section['key']}.pdf",
            "json_file":   f"{section['key']}.json",
            "word_count":  word_count,
        })

    return metadata_rows


def write_xlsx(metadata_rows: list[dict], output_path: str):
    df = pd.DataFrame(metadata_rows)
    df.to_excel(output_path, index=False)
    print(f"✓ resources.xlsx written → {output_path}")


# ── CLI ───────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Split Iron Arrow PDF and generate 4-layer chunks.")
    parser.add_argument("--input",      required=True,              help="Path to source PDF")
    parser.add_argument("--output_dir", default="./sections",       help="Where to write split PDFs")
    parser.add_argument("--chunks_dir", default="./chunks",         help="Where to write JSON chunks")
    parser.add_argument("--xlsx",       default="./resources.xlsx", help="Output metadata file")
    args = parser.parse_args()

    rows = split_pdf(args.input, args.output_dir, args.chunks_dir)
    write_xlsx(rows, args.xlsx)
    print("\nDone. Verify page boundaries by opening each split PDF before wiring into the chatbot.")
